global class LeadProcessor implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
        	'SELECT Id, LeadSource, Company FROM Lead'
        );
    }
    global void execute(Database.BatchableContext bc, List<Lead> scope) {
        for (Lead dbLead : scope) {
            dbLead.LeadSource = 'Dreamforce';
        }
        update scope;
    }
    global void finish(Database.BatchableContext bc) {
        
    }
}